/**
 * @File Name          : ApexClassTest.cls
 * @Description        : 
 * @Author             : Mario Oliveira
 * @Group              : 
 * @Last Modified By   : Mario Oliveira
 * @Last Modified On   : 13/12/2019 18:23:05
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    13/12/2019   Mario Oliveira     Initial Version
**/
public with sharing class ApexClassTest {
    public static void Test() {
        System.debug('Teste');
    }
}
